version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build-and-deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install:
          node-version: '16.13'
      - checkout
      - aws-cli/setup
      - eb/setup
# Installing the frontend dependencies
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
# Installing the Backend dependencies
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
# Building the frontend
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
# Building the backend
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
# Installing AWS Elastic Beanstalk CLI
      - run:
          name: Installing AWS Elasticbeanstalk
          command: |
            npm run backend:aws-eb
# SET AWS Region 
      - run:
          name: Region-Set
          command: |
            npm run region-set
# Deploying the backend to AWS Elastic Beanstalk
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
# Deploying the frontend to AWS S3
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main