version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0

jobs:
   build-and-deploy:
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
# Installing the frontend dependencies
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
     

# Building the frontend
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
# Deploying the frontend to AWS S3
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
# Installing the Backend dependencies
      - run:
          name: Back-End Install
          command: |
            npm run backend:install

# Building the backend
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
# Installing AWS Elastic Beanstalk CLI
      - run:
          name: Installing AWS Elasticbeanstalk
          command: |
            npm run backend:aws-eb
# Deploying the backend to AWS Elastic Beanstalk
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context: aws
          filters:
            branches:
              only:
                - main